AWSTemplateFormatVersion: "2010-09-09"

Description: Amazon EKS - Bastion EC2 Kubeconfig Role

Mappings:
  ServicePrincipals:
    aws-cn:
      ec2: ec2.amazonaws.com.cn
    aws:
      ec2: ec2.amazonaws.com

Resources:
  BastionInstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - !FindInMap [ServicePrincipals, !Ref "AWS::Partition", ec2]
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: EKSBastionPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'eks:DescribeCluster'
                Resource: '*'

  BastionInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref BastionInstanceRole

Outputs:
  NodeInstanceRole:
    Description: The bastion instance role
    Value: !GetAtt BastionInstanceRole.Arn
